global:
  weight:
    target_dtype: fp8_e4m3
    calibrator: "minmax"  
    granularity: "block"  
    is_sym: True
  activation:
    target_dtype: int8
    calibrator: "minmax"  
    granularity: "dynamic"  
    is_sym: True
  algorithm: 
    minmax:
      is_sym: True
  
local:
  self_attn:
    activation:
      calibrator: "minmax" 
    weight:
      target_dtype: int8  
      calibrator: "minmax"  
      granularity: "channel"  

disable:
  ["*lm_head*"]

max_layers_per_subgraph: 5

is_training: False

quant_type: "fp8_e4m3"
quant_target: "sglang"
  